-- Создание таблицы clinic для хранения информации о клиниках
CREATE SCHEMA IF NOT EXISTS ms_clinic_sc;

CREATE TABLE IF NOT EXISTS ms_clinic_sc.clinic
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(252) NOT NULL UNIQUE,
    description TEXT,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- Создание таблицы address для хранения адресов клиник
CREATE TABLE IF NOT EXISTS ms_clinic_sc.address
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id       INT REFERENCES ms_clinic_sc.clinic (id) ON DELETE CASCADE UNIQUE,
    city            VARCHAR(128) NOT NULL,
    street          VARCHAR(252) NOT NULL,
    building_number VARCHAR(32)  NOT NULL,
    UNIQUE (id, clinic_id, city, street, building_number)
);

-- Создание таблицы contact_info для хранения контактной информации клиник
CREATE TABLE IF NOT EXISTS ms_clinic_sc.contact_info
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id  INT REFERENCES ms_clinic_sc.clinic (id) ON DELETE CASCADE UNIQUE,
    work_phone VARCHAR(32)  NOT NULL,
    work_email VARCHAR(252) NOT NULL,
    UNIQUE (id, clinic_id, work_phone, work_email)
);